services:
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file:
      - .env.example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lyceum-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data:
