# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: lyceum
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmQ1NGYwMjYxMzc2NjA2YjhjOTcyYjc4MzlkNDc5YjM1NDEyYjEyOTkxODIyM2M4ZWY1ZmE0N2IzMDI2YzJiOGM1YjRhOTFiMDZjYzE3NmQ4ZjVlMTIxY2I4YjcxZjEzZjk3YjA3NTIxMWZjY2M1NjMzODY2MzNkYzVhMDg1ZmY=
