spring.application.name=lyceum-backend

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1QgdXNlZCBpbiBseWNldW0gYXBwbGljYXRpb24=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
